Repository Les-Jailes/Boutique_Clothing, pull requests merged in 2023-11, with the labels that each got.

#2 FEATURE/US-1/PRODUCTS PAGE
  package-lock.json
  package.json
  public/cart.png
  public/menu-bar.png
  public/user-profile.png
  src/app/globals.css
  src/app/layout.js
  src/app/page.jsx
  src/app/pages/about-us/loading.jsx
  src/app/pages/about-us/page.jsx
  src/app/pages/about-us/page.module.css
  src/app/pages/contact-us/loading.jsx
  src/app/pages/contact-us/page.jsx
  src/app/pages/contact-us/page.module.css
  src/app/pages/products/page.jsx
  src/app/pages/settings/loading.jsx
  src/app/pages/settings/page.jsx
  src/app/pages/settings/page.module.css
  src/app/pages/shopping-cart/loading.jsx
  src/app/pages/shopping-cart/page.jsx
  src/app/pages/shopping-cart/page.module.css
  src/app/pages/user-profile/loading.jsx
  src/app/pages/user-profile/page.jsx
  src/app/pages/user-profile/page.module.css
  src/app/user-profile/page.module.css
  src/components/Products/ClotheCard.jsx
  src/components/Products/ColorClothe.jsx
  src/components/Products/Pagination.jsx
  src/components/navbar/Navbar.jsx
  src/components/navbar/dropdown/dropdown.module.css
  src/components/navbar/menuItems/MenuItems.jsx
  src/components/navbar/menuItems/menu.module.css
  src/components/navbar/navbar.module.css
  src/components/navbar/navbarFooter/navfooter.module.css
  src/css/General.css
  src/css/Products/ClotheCard.css
  src/css/Products/ColorClothe.css
  src/css/Products/Pagination.css
  src/css/Products/ProductsPage.css
  src/utils/Pagination.js
  src/utils/navfooterItems.js
Labels: feuture

#4 Feature/us 17/user authentication login
  .env
  package-lock.json
  package.json
  public/bg-login.png
  public/login-bg.jpeg
  src/app/api/auth/[...nextauth]/route.js
  src/app/layout.js
  src/app/pages/account/login/page.jsx
  src/app/pages/account/login/page.module.css
  src/app/pages/account/signup/page.jsx
  src/app/pages/user-profile/page.jsx
  src/components/authProvider/AuthProvider.jsx
  src/model/User.js
  src/utils/dbUtil.js
  src/utils/formValidations.js
  src/utils/menuItems.js
Labels: feuture

#5 Feature/us 21/footer UI implementation
  public/logo2.png
  public/logoWhite.png
  src/app/globals.css
  src/app/layout.js
  src/components/footer/Footer.jsx
  src/components/footer/footer.module.css
  src/utils/footerItems.js
Labels: Feature

#6 Feature/us 13/cart page UI creation
  package-lock.json
  src/app/pages/shopping-cart/page.jsx
  src/app/pages/shopping-cart/page.module.css
  src/components/navbar/Cart/CartButton.jsx
  src/components/navbar/Cart/CartCardSummary.jsx
  src/components/navbar/Cart/CartListSummary.jsx
  src/components/navbar/Cart/ShoppingCart/CardProductCart.jsx
  src/components/navbar/Cart/ShoppingCart/CheckOutButton.jsx
  src/components/navbar/Cart/ShoppingCart/OrderSummary.jsx
  src/components/navbar/Cart/ShoppingCart/QuantityProduct.jsx
  src/components/navbar/Navbar.jsx
  src/components/navbar/menuItems/MenuItems.jsx
  src/css/Cart/CardProductCart.css
  src/css/Cart/CartButton.css
  src/css/Cart/CartCardSummary.css
  src/css/Cart/CartListSummary.css
  src/css/Cart/CheckoutButton.css
  src/css/Cart/OrderSummary.css
  src/css/Cart/QuantityProducts.css
  src/css/Cart/ShoppingCart.css
  src/css/General.css
  src/utils/ExampleSummary.js
  src/utils/OrderSummary.js
  src/utils/menuItems.js
  src/utils/navfooterItems.js
Labels: Feature

#9 Feature/us 16/sign up
  package-lock.json
  package.json
  public/signup-bg.jpg
  src/app/api/api.js
  src/app/pages/account/signup/confirmationAlert.js
  src/app/pages/account/signup/page.jsx
  src/app/pages/account/signup/page.module.css
  src/utils/formValidations.js
Labels: Feature

#11 Feature/US-25/Google-authentication-on-sign-up
  src/app/pages/account/login/page.jsx
  src/app/pages/account/signup/page.jsx
  src/app/pages/account/signup/page.module.css
  src/css/GoogleAuthenticationStyles/GoogleButtonStyles.css
Labels: Feature

#14 Feature/us 30/about us UI
  public/axel.jpg
  public/bgAboutusAIBossted.jpg
  public/carlos.jpg
  public/culture.jpg
  public/dennis.jpg
  public/elvis.jpg
  public/history.jpg
  public/salet.jpg
  public/values.jpg
  public/victor.jpg
  public/vision.jpg
  src/app/pages/about-us/page.jsx
  src/app/pages/about-us/page.module.css
  src/components/about-us/MainBox.jsx
  src/components/about-us/imgSlider/ImgSlider.jsx
  src/components/about-us/imgSlider/slider.module.css
  src/components/about-us/infoBox/InformationBox.jsx
  src/components/about-us/infoBox/infobox.module.css
  src/components/about-us/mainbox.module.css
  src/utils/aboutUsUtils.js
Labels: Feature

#18 ID 14 - Delete item in the cart
  src/components/ShoppingCart/CardProductCart.jsx
  src/components/navbar/Cart/CartButton.jsx
  src/components/navbar/Cart/CartCardSummary.jsx
  src/components/navbar/Cart/CartListSummary.jsx
  src/css/Cart/CartCardSummary.css
  src/css/Cart/CartListSummary.css
Labels: Feature

#20 ID 37 - Navigation to social networks in the footer
  src/utils/footerItems.js
Labels: Feature

#23 bugs 03 and 05 fixed in about us
  src/components/about-us/imgSlider/ImgSlider.jsx
  src/components/about-us/imgSlider/slider.module.css
  src/components/about-us/infoBox/infobox.module.css
Labels: bug

#25 Feature/us 36/category display UI
  public/Swimwearw.png
  public/bootees.png
  public/boxers.png
  public/coats.png
  public/dress.png
  public/groom-suit.png
  public/panties.png
  public/pants.png
  public/shirts.png
  public/skirt.png
  public/skirts.png
  public/suitsm.png
  public/suitsw.png
  public/swearters.png
  public/swimsuit.png
  public/swimwear.png
  public/t-shirts.png
  public/underwear.png
  src/app/pages/user-profile/page.jsx
  src/components/navbar/navbarFooter/NavbarFooter.jsx
  src/components/navbar/navbarFooter/navfooter.module.css
  src/utils/navfooterItems.js
Labels: Feature

#27 testing deployment
  src/app/pages/products/page.jsx
  src/app/pages/products/page.module.css
  src/components/filter/Filter.jsx
  src/components/filter/filter.module.css
  src/components/filter/filterCheckbox/FilterCheckbox.jsx
  src/components/filter/filterCheckbox/fcheckbox.module.css
  src/utils/Pagination.js
  src/utils/footerItems.js
Labels: deployment

#22 Bug/ID-04/validation error when registering an account with google using an email already registered with credentials
  package-lock.json
  package.json
  src/app/api/auth/[...nextauth]/route.js
  src/app/layout.js
  src/app/pages/account/login/page.jsx
  src/components/Alerts/CustomToast.jsx
Labels: bug

#32 BUG-08-07-fix/PopUpAndDeteleteItemsError
  src/components/navbar/Cart/CartCardSummary.jsx
Labels: bug

#34 Testing deployment
  src/components/navbar/Cart/CartCardSummary.jsx
Labels: deployment

#33 Feature/us 34/checkout with stripe functionality
  package-lock.json
  package.json
  src/app/pages/checkout/payment/page.jsx
  src/app/pages/checkout/payment/page.module.css
  src/components/Checkout/CheckoutForm.jsx
  src/components/Checkout/CountryDropdown.jsx
  src/components/Products/CartContext.jsx
  src/components/Stripe/Checkout.jsx
  src/css/StripeStyles/Checkout.css
  src/css/StripeStyles/CheckoutPayment.css
Labels: Feature

#37 deployment
  package-lock.json
  package.json
  src/app/pages/checkout/payment/page.jsx
  src/app/pages/checkout/payment/page.module.css
  src/components/Checkout/CheckoutForm.jsx
  src/components/Checkout/CountryDropdown.jsx
  src/components/Products/CartContext.jsx
  src/components/Stripe/Checkout.jsx
  src/components/navbar/navbarFooter/navfooter.module.css
  src/css/StripeStyles/Checkout.css
  src/css/StripeStyles/CheckoutPayment.css
Labels: deployment

#40 [BUG] ID - 08 - Popup cart status handling error when removing products from the Shopping Cart page
  src/app/layout.js
Labels: bug

#44 Deploy
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.js
  src/app/page.jsx
  src/app/pages/account/login/page.jsx
  src/app/pages/cateogories/page.jsx
  src/app/pages/products/page.jsx
  src/app/pages/user-profile/page.jsx
  src/components/Home/Categories/Categories.jsx
  src/components/Home/Cover/Carousel.jsx
  src/components/Home/Cover/Cover.jsx
  src/components/Home/Cover/CoverElement.jsx
  src/components/Home/OurProducts/MultiSlider.jsx
  src/components/Home/OurProducts/OurProducts.jsx
  src/components/Products/ClotheCard.jsx
  src/components/navbar/navbarFooter/NavbarFooter.jsx
  src/css/Home/Categories/Categories.css
  src/css/Home/Categories/Category.css
  src/css/Home/Cover/Cover.css
  src/css/Home/MostPopular/MostPopular.css
  src/utils/Carousel.json
  src/utils/CategoriesHome.json
  src/utils/SizePopup.jsx
  src/utils/navfooterItems.js
Labels: deployment

#43 404 not found page implementation
  public/bg-404.jpg
  src/app/globals.css
  src/app/not-found.jsx
Labels: task

#45 BUG 19 - fix
  .env
  .gitignore
  src/app/api/api.js
  src/app/pages/account/login/page.jsx
  src/app/pages/account/signup/confirmationAlert.js
Labels: bug

#42 Feature/US-42/Payment Validation Handler
  src/app/pages/account/login/page.jsx
  src/app/pages/checkout/page.jsx
  src/app/pages/products/page.jsx
  src/components/Products/CartContext.jsx
  src/components/Stripe/Checkout.jsx
Labels: Feature

#46 Deploy
  .env
  .gitignore
  public/bg-404.jpg
  src/app/api/api.js
  src/app/globals.css
  src/app/not-found.jsx
  src/app/pages/account/login/page.jsx
  src/app/pages/account/signup/confirmationAlert.js
  src/app/pages/checkout/page.jsx
  src/app/pages/products/page.jsx
  src/components/Products/CartContext.jsx
  src/components/Stripe/Checkout.jsx
Labels: deployment

#49 Depolyment
  src/app/pages/products/page.jsx
  src/app/pages/shopping-cart/page.jsx
  src/components/Checkout/Summary.jsx
  src/components/Products/CartContext.jsx
  src/components/ShoppingCart/CardProductCart.jsx
  src/components/ShoppingCart/CheckOutButton.jsx
  src/components/ShoppingCart/QuantityProduct.jsx
  src/components/ShoppingCart/SoldOut.jsx
  src/components/navbar/Cart/CartCardSummary.jsx
  src/css/Cart/CardProductCart.css
  src/css/Cart/CartCardSummary.css
  src/css/Cart/CheckoutButton.css
  src/css/Cart/QuantityProducts.css
  src/css/Cart/SoldOut.css
  src/utils/SizePopup.jsx
  src/utils/alerts.js
Labels: deployment

#52 Deployment
  src/components/Checkout/Summary.jsx
  src/components/Products/CartContext.jsx
Labels: deployment

#54 Deployment
  src/components/Products/CartContext.jsx
Labels: deployment

#55 Deploy
  src/app/pages/checkout/page.jsx
  src/components/Stripe/Checkout.jsx
Labels: deployment

#57 bug/ID-20/When-entering-to-profile-info-screen-after-sign-up-with-google-CI-field-is-filled-with-a-too-large-number
  src/app/api/auth/[...nextauth]/route.js
Labels: bug

#56 Bug/ID-15/Lack of validation to show the have products in cart alert when a purchase has been successfully completed
  src/components/Stripe/Checkout.jsx
Labels: bug

#60 Feature/us cu 8686h0r2p/bug id 26 application crashes when filtering products by size
  src/app/pages/products/page.jsx
  src/components/filter/Filter.jsx
  src/components/filter/filterCheckbox/fcheckbox.module.css
Labels: bug

#61 Feature/us cu 8686hk6r5/id 51 categories page implementation for genders
  src/app/pages/products/boy/page.jsx
  src/app/pages/products/boy/page.module.css
  src/app/pages/products/girl/page.jsx
  src/app/pages/products/girl/page.module.css
  src/app/pages/products/men/page.jsx
  src/app/pages/products/men/page.module.css
  src/app/pages/products/women/page.jsx
  src/app/pages/products/women/page.module.css
  src/components/Home/Categories/Categories.jsx
  src/components/navbar/navbarFooter/NavbarFooter.jsx
  src/components/navbar/navbarFooter/navfooter.module.css
  src/utils/SideMenuItems.json
  src/utils/navfooterItems.js
Labels: Feature

#58 BUG - ID 21 On-profile-info-screen-CI-field-doesnt-allow-to-put-0-digits
  src/utils/formValidations.js
Labels: bug

#59 BUG - ID 22 When-editing-profile-info-options-displayed-to-edit-users-genre-have-letter-with-blank-color
  src/app/pages/user-profile/UserProfile.css
  src/app/pages/user-profile/page.jsx
Labels: bug

#65 [BUG] ID-17: The "street address" field has no character limit
  src/components/Checkout/CheckoutForm.jsx
  src/components/Checkout/Summary.jsx
  src/utils/formValidations.js
Labels: bug

#66 Deploy
  src/app/pages/user-profile/UserProfile.css
  src/app/pages/user-profile/page.jsx
  src/components/Checkout/CheckoutForm.jsx
  src/components/Checkout/Summary.jsx
  src/utils/formValidations.js
Labels: deployment

#68 Feature/us cu 8686hh8vv/id 50 contact us page
  next.config.js
  public/contactus_bg.jpg
  src/app/pages/contact-us/page.jsx
  src/app/pages/contact-us/page.module.css
Labels: Feature

#69 deployment
  next.config.js
  public/contactus_bg.jpg
  src/app/pages/contact-us/page.jsx
  src/app/pages/contact-us/page.module.css
Labels: deployment

#71 Deploy
  next.config.js
  src/app/pages/checkout/page.jsx
  src/app/pages/user-profile/page.jsx
  src/components/Checkout/CheckoutField.jsx
  src/components/Checkout/CheckoutForm.jsx
  src/components/Checkout/DropDownCountries.jsx
  src/components/Checkout/Summary.jsx
  src/components/Products/CartContext.jsx
  src/components/ShoppingCart/OrderSummary.jsx
  src/components/footer/footer.module.css
  src/css/Checkout/CheckoutField.css
  src/css/Checkout/CheckoutForm.css
  src/css/Checkout/DropDownCountries.css
  src/css/Checkout/Summary.css
  src/utils/formValidations.js
Labels: deployment

#63 login responsiveness on box width fix
  src/app/pages/account/login/page.module.css
  src/components/navbar/navbar.module.css
Labels: bug

#73 Deploy
  src/app/pages/account/login/page.module.css
  src/components/navbar/navbar.module.css
Labels: deployment

#74 Deploy
  src/app/pages/searcher/page.jsx
  src/components/navbar/Navbar.jsx
  src/components/navbar/SideMenu/SearchBarSideMenu.jsx
  src/components/navbar/navbar.module.css
  src/components/navbar/navbarFooter/NavbarFooter.jsx
  src/css/Products/ProductsPage.css
  src/css/SideMenu/SearchBarSideMenu.css
Labels: deployment

#76 Deploy
  src/app/pages/account/login/page.jsx
  src/app/pages/account/login/page.module.css
  src/app/pages/user-profile/UserProfile.css
  src/app/pages/user-profile/order-history/page.jsx
  src/app/pages/user-profile/page.jsx
Labels: deployment

#77 Deployment
  next.config.js
  src/app/globals.css
  src/app/pages/account/login/page.jsx
  src/app/pages/products/page.module.css
  src/app/pages/user-profile/my-wishlist/NoProductsFound.jsx
  src/app/pages/user-profile/my-wishlist/page.jsx
  src/components/Products/ClotheCard.jsx
  src/components/navbar/Navbar.jsx
  src/css/Loader/Loader.css
  src/css/Products/ClotheCard.css
  src/css/Products/ProductsPage.css
  src/utils/Loader.jsx
Labels: deployment
